In [ ]:
import numpy as np
import pandas as pd
import os
from sksurv.util import Surv
from sksurv.linear_model import CoxnetSurvivalAnalysis

In [3]:
BASE_DATA_PATH = '../data/input_data/'
dataset_path = os.path.join('Borrow', 'Deposit')

print("Loading data...")
try:
    train_df = pd.read_csv(os.path.join(BASE_DATA_PATH, dataset_path, 'train.csv'))
except FileNotFoundError as e:
    print(f"Training data for {dataset_path} not found. Skipping. Details: {e}")

Loading data...

In [28]:
from utilities.preprocessing import preprocess
print("Preprocessing data...")
X_train, y_train, _ = preprocess(train_df)

Preprocessing data...
  - Dropping 3 zero-variance columns: ['userCoinTypeMode_Other', 'coinType_Other', 'reserve_Other']

In [29]:
# Convert X to float numpy array
X_train = np.asarray(X_train, dtype=float)

# Convert y to (time, event) float array
y_train = np.column_stack([
    train_df["timeDiff"].astype(float).values,
    train_df["status"].astype(int).values
])

In [31]:
from lassonet import LassoNetCoxRegressor

model = LassoNetCoxRegressor(tie_approximation="breslow")
model.fit(X_train, y_train)
# oracle, order, wrong, paths, prob = model.stability_selection(X_train, y_train)

OutOfMemoryError: CUDA out of memory. Tried to allocate 342.00 MiB. GPU 0 has a total capacity of 31.73 GiB of which 338.44 MiB is free. Process 3827274 has 516.00 MiB memory in use. Process 1382176 has 30.59 GiB memory in use. Including non-PyTorch memory, this process has 306.00 MiB memory in use. Of the allocated memory 0 bytes is allocated by PyTorch, and 0 bytes is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

In [ ]:
from lifelines import CoxPHFitter

cph = CoxPHFitter()

print("Training model on full training data...")
lifelines_train_df = pd.concat([X_train, y_train.reset_index(drop=True)], axis=1)
        
model = CoxPHFitter(penalizer=0.1)
model.fit(lifelines_train_df, duration_col='timeDiff', event_col='status')

Training model on full training data...

In [ ]:
model.print_summary()

<lifelines.CoxPHFitter: fitted with 882736 total observations, 504835 right-censored observations>
             duration col = 'timeDiff'
                event col = 'status'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 882736
number of events observed = 377901
   partial log-likelihood = -4935950.25
         time fit was run = 2025-09-17 19:05:13 UTC

---
                                     coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
userActiveDaysWeekly                 0.18      1.19      0.00            0.17            0.18                1.19                1.20
marketLiquidationSumUSD             -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
marketLiquidationAvgAmountUSD        0.01      1.01      0.00            0.01            0.02                1.01                1.02
userBorrowSum                       -0.08      0.92      0.00           -0.09           -0.07                0.92                0.93
userDepositAvgAmountUSD              0.03      1.03      0.00            0.03            0.04                1.03                1.04
cosQuarter                           0.01      1.01      0.00            0.01            0.02                1.01                1.02
userWithdrawAvgAmountUSD            -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
userRepaySumUSD                     -0.09      0.91      0.00           -0.10           -0.09                0.90                0.92
userLiquidationAvgAmountUSD          0.02      1.02      0.00            0.01            0.02                1.01                1.02
userRepayCount                      -0.17      0.84      0.00           -0.18           -0.16                0.84                0.85
cosDayOfYear                         0.05      1.05      0.00            0.04            0.05                1.04                1.05
marketWithdrawSumUSD                -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userWithdrawAvgAmount               -0.05      0.95      0.00           -0.06           -0.05                0.94                0.95
marketRepayAvgAmount                -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketDepositCount                   0.00      1.00      0.00           -0.00            0.01                1.00                1.01
userBorrowAvgAmount                 -0.06      0.94      0.00           -0.06           -0.05                0.94                0.95
marketLiquidationCount               0.02      1.02      0.00            0.02            0.03                1.02                1.03
userSecondsSinceFirstTransaction     0.01      1.01      0.00            0.01            0.01                1.01                1.02
sinDayOfQuarter                     -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userDepositCount                     0.21      1.24      0.00            0.21            0.22                1.23                1.24
quarter                             -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
dayOfYear                           -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
userRepayAvgAmount                   0.02      1.02      0.00            0.02            0.03                1.02                1.03
marketBorrowCount                    0.04      1.04      0.00            0.03            0.04                1.03                1.04
marketLiquidationAvgAmount           0.03      1.03      0.00            0.03            0.04                1.03                1.04
userWithdrawCount                    0.02      1.02      0.00            0.02            0.02                1.02                1.02
sinTimeOfDay                        -0.03      0.97      0.00           -0.03           -0.03                0.97                0.97
cosDayOfWeek                         0.00      1.00      0.00           -0.00            0.01                1.00                1.01
marketWithdrawCount                 -0.04      0.96      0.00           -0.04           -0.03                0.96                0.97
marketRepayAvgAmountUSD              0.03      1.03      0.00            0.03            0.04                1.03                1.04
amount                               0.01      1.01      0.00            0.01            0.02                1.01                1.02
userLiquidationAvgAmount             0.04      1.04      0.00            0.03            0.04                1.03                1.04
logAmount                            0.03      1.03      0.00            0.02            0.03                1.03                1.04
priceInUSD                          -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
marketBorrowSum                      0.01      1.01      0.00            0.00            0.02                1.00                1.02
marketDepositAvgAmountUSD            0.02      1.02      0.00            0.02            0.03                1.02                1.03
marketRepaySum                       0.01      1.01      0.00            0.00            0.01                1.00                1.01
cosTimeOfDay                         0.00      1.00      0.00           -0.00            0.00                1.00                1.00
userDepositSumUSD                   -0.03      0.97      0.00           -0.03           -0.02                0.97                0.98
sinDayOfYear                         0.07      1.07      0.00            0.06            0.07                1.07                1.08
timeOfDay                            0.01      1.01      0.00            0.00            0.01                1.00                1.01
marketRepaySumUSD                    0.04      1.04      0.00            0.03            0.05                1.03                1.05
dayOfQuarter                         0.00      1.00      0.00            0.00            0.01                1.00                1.01
userSecondsSincePreviousTransaction -0.07      0.93      0.00           -0.07           -0.06                0.93                0.94
marketBorrowSumUSD                   0.04      1.04      0.00            0.04            0.05                1.04                1.05
userLiquidationSumUSD               -0.07      0.93      0.00           -0.07           -0.06                0.93                0.94
sinDayOfMonth                        0.01      1.01      0.00            0.01            0.02                1.01                1.02
userActiveDaysMonthly                0.16      1.17      0.00            0.15            0.16                1.17                1.18
sinDayOfWeek                        -0.00      1.00      0.00           -0.01           -0.00                0.99                1.00
marketDepositSum                    -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
marketDepositSumUSD                  0.00      1.00      0.00           -0.00            0.01                1.00                1.01
marketWithdrawSum                   -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketLiquidationSum                -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userRepayAvgAmountUSD               -0.03      0.97      0.00           -0.04           -0.02                0.96                0.98
dayOfMonth                          -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketWithdrawAvgAmountUSD           0.04      1.05      0.00            0.04            0.05                1.04                1.05
marketBorrowAvgAmountUSD             0.01      1.01      0.00            0.00            0.02                1.00                1.02
marketDepositAvgAmount               0.00      1.00      0.00           -0.00            0.01                1.00                1.01
userDepositSum                      -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
userBorrowAvgAmountUSD              -0.11      0.90      0.00           -0.11           -0.10                0.89                0.90
marketBorrowAvgAmount               -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
isWeekend                           -0.01      0.99      0.01           -0.02            0.00                0.98                1.00
userLiquidationCount                 0.07      1.07      0.00            0.06            0.07                1.06                1.07
userActiveDaysYearly                 0.00      1.00      0.00           -0.00            0.01                1.00                1.01
userIsNew                           -0.98      0.37      0.03           -1.04           -0.93                0.36                0.39
sinQuarter                          -0.04      0.96      0.00           -0.05           -0.04                0.96                0.96
marketWithdrawAvgAmount              0.02      1.02      0.00            0.02            0.03                1.02                1.03
logAmountUSD                         0.14      1.15      0.00            0.14            0.15                1.15                1.16
dayOfWeek                           -0.00      1.00      0.00           -0.00            0.00                1.00                1.00
userRepaySum                        -0.08      0.92      0.00           -0.08           -0.07                0.92                0.93
userLiquidationSum                   0.07      1.07      0.00            0.06            0.07                1.06                1.07
userWithdrawSumUSD                  -0.03      0.97      0.00           -0.04           -0.03                0.97                0.97
amountUSD                           -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
userBorrowCount                     -0.18      0.84      0.00           -0.19           -0.17                0.83                0.84
cosDayOfQuarter                     -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
marketRepayCount                    -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
userBorrowSumUSD                    -0.09      0.91      0.00           -0.10           -0.09                0.90                0.91
userWithdrawSum                     -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userDepositAvgAmount                -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
cosDayOfMonth                        0.01      1.01      0.00            0.00            0.01                1.00                1.01
userCoinTypeMode_Stable              0.04      1.04      0.01            0.03            0.05                1.03                1.05
userCoinTypeMode_Non-Stable         -0.04      0.96      0.01           -0.05           -0.03                0.95                0.97
coinType_Stable                      0.04      1.04      0.01            0.03            0.05                1.03                1.05
coinType_Non-Stable                 -0.04      0.96      0.01           -0.05           -0.03                0.95                0.97
userReserveMode_USDC                 0.25      1.29      0.01            0.24            0.27                1.27                1.30
userReserveMode_DAI                 -0.16      0.85      0.01           -0.18           -0.15                0.84                0.86
userReserveMode_WPOL                -0.02      0.98      0.01           -0.04           -0.01                0.96                0.99
userReserveMode_WETH                 0.10      1.10      0.01            0.08            0.12                1.09                1.12
userReserveMode_USDT                -0.18      0.83      0.01           -0.20           -0.17                0.82                0.85
userReserveMode_WBTC                 0.25      1.28      0.01            0.22            0.27                1.25                1.31
userReserveMode_GHST                -0.76      0.47      0.01           -0.78           -0.74                0.46                0.48
userReserveMode_LINK                 0.21      1.24      0.01            0.19            0.24                1.20                1.27
userReserveMode_EURS                -0.22      0.80      0.02           -0.25           -0.18                0.78                0.83
userReserveMode_MaticX               0.35      1.42      0.02            0.32            0.38                1.37                1.47
userReserveMode_Other               -0.14      0.87      0.01           -0.16           -0.11                0.85                0.89
reserve_USDC                         0.25      1.29      0.01            0.24            0.27                1.27                1.30
reserve_other                       -0.27      0.76      0.01           -0.28           -0.26                0.75                0.77
reserve_WPOL                        -0.02      0.98      0.01           -0.04           -0.01                0.96                0.99
reserve_WETH                         0.10      1.10      0.01            0.08            0.12                1.09                1.12
reserve_USDT                        -0.18      0.83      0.01           -0.20           -0.17                0.82                0.85
reserve_WBTC                         0.25      1.28      0.01            0.22            0.27                1.25                1.31

                                     cmp to      z      p  -log2(p)
covariate
userActiveDaysWeekly                   0.00  81.08 <0.005       inf
marketLiquidationSumUSD                0.00  -8.05 <0.005     50.04
marketLiquidationAvgAmountUSD          0.00   5.87 <0.005     27.80
userBorrowSum                          0.00 -25.39 <0.005    470.08
userDepositAvgAmountUSD                0.00  14.91 <0.005    164.61
cosQuarter                             0.00   4.20 <0.005     15.19
userWithdrawAvgAmountUSD               0.00 -42.38 <0.005       inf
userRepaySumUSD                        0.00 -30.26 <0.005    665.91
userLiquidationAvgAmountUSD            0.00   8.67 <0.005     57.72
userRepayCount                         0.00 -55.64 <0.005       inf
cosDayOfYear                           0.00  20.18 <0.005    298.50
marketWithdrawSumUSD                   0.00  -0.54   0.59      0.77
userWithdrawAvgAmount                  0.00 -18.96 <0.005    263.99
marketRepayAvgAmount                   0.00  -4.36 <0.005     16.20
marketDepositCount                     0.00   1.53   0.13      2.98
userBorrowAvgAmount                    0.00 -20.02 <0.005    293.77
marketLiquidationCount                 0.00  10.13 <0.005     77.64
userSecondsSinceFirstTransaction       0.00   6.90 <0.005     37.47
sinDayOfQuarter                        0.00  -7.71 <0.005     46.19
userDepositCount                       0.00  99.67 <0.005       inf
quarter                                0.00  -1.22   0.22      2.16
dayOfYear                              0.00  -0.83   0.41      1.29
userRepayAvgAmount                     0.00   8.68 <0.005     57.80
marketBorrowCount                      0.00  14.64 <0.005    158.76
marketLiquidationAvgAmount             0.00  12.80 <0.005    122.23
userWithdrawCount                      0.00  12.10 <0.005    109.46
sinTimeOfDay                           0.00 -16.25 <0.005    194.91
cosDayOfWeek                           0.00   1.77   0.08      3.71
marketWithdrawCount                    0.00 -12.48 <0.005    116.25
marketRepayAvgAmountUSD                0.00  10.91 <0.005     89.63
amount                                 0.00   5.20 <0.005     22.23
userLiquidationAvgAmount               0.00  21.82 <0.005    348.06
logAmount                              0.00  11.64 <0.005    101.54
priceInUSD                             0.00  -0.58   0.56      0.83
marketBorrowSum                        0.00   3.34 <0.005     10.22
marketDepositAvgAmountUSD              0.00   8.48 <0.005     55.26
marketRepaySum                         0.00   2.15   0.03      4.97
cosTimeOfDay                           0.00   1.23   0.22      2.19
userDepositSumUSD                      0.00 -10.58 <0.005     84.51
sinDayOfYear                           0.00  26.80 <0.005    523.01
timeOfDay                              0.00   3.65 <0.005     11.91
marketRepaySumUSD                      0.00  13.08 <0.005    127.38
dayOfQuarter                           0.00   2.04   0.04      4.61
userSecondsSincePreviousTransaction    0.00 -32.17 <0.005    752.03
marketBorrowSumUSD                     0.00  13.96 <0.005    144.81
userLiquidationSumUSD                  0.00 -33.07 <0.005    794.20
sinDayOfMonth                          0.00   6.49 <0.005     33.46
userActiveDaysMonthly                  0.00  68.44 <0.005       inf
sinDayOfWeek                           0.00  -2.00   0.05      4.46
marketDepositSum                       0.00  -2.83 <0.005      7.74
marketDepositSumUSD                    0.00   1.40   0.16      2.62
marketWithdrawSum                      0.00  -4.16 <0.005     14.94
marketLiquidationSum                   0.00  -6.84 <0.005     36.84
userRepayAvgAmountUSD                  0.00 -10.81 <0.005     88.07
dayOfMonth                             0.00  -6.44 <0.005     32.94
marketWithdrawAvgAmountUSD             0.00  16.79 <0.005    207.81
marketBorrowAvgAmountUSD               0.00   3.27 <0.005      9.88
marketDepositAvgAmount                 0.00   0.45   0.65      0.62
userDepositSum                         0.00  -5.22 <0.005     22.43
userBorrowAvgAmountUSD                 0.00 -36.57 <0.005    970.14
marketBorrowAvgAmount                  0.00  -7.59 <0.005     44.84
isWeekend                              0.00  -1.73   0.08      3.58
userLiquidationCount                   0.00  47.02 <0.005       inf
userActiveDaysYearly                   0.00   1.17   0.24      2.05
userIsNew                              0.00 -36.43 <0.005    962.90
sinQuarter                             0.00 -17.19 <0.005    217.51
marketWithdrawAvgAmount                0.00   8.18 <0.005     51.67
logAmountUSD                           0.00  56.96 <0.005       inf
dayOfWeek                              0.00  -0.08   0.94      0.09
userRepaySum                           0.00 -25.36 <0.005    469.07
userLiquidationSum                     0.00  33.69 <0.005    824.03
userWithdrawSumUSD                     0.00 -13.12 <0.005    128.29
amountUSD                              0.00  -4.21 <0.005     15.27
userBorrowCount                        0.00 -59.00 <0.005       inf
cosDayOfQuarter                        0.00  -9.37 <0.005     66.89
marketRepayCount                       0.00  -3.37 <0.005     10.39
userBorrowSumUSD                       0.00 -30.29 <0.005    666.87
userWithdrawSum                        0.00  -8.13 <0.005     51.06
userDepositAvgAmount                   0.00  -6.55 <0.005     33.99
cosDayOfMonth                          0.00   3.63 <0.005     11.78
userCoinTypeMode_Stable                0.00   6.42 <0.005     32.78
userCoinTypeMode_Non-Stable            0.00  -6.42 <0.005     32.78
coinType_Stable                        0.00   6.42 <0.005     32.78
coinType_Non-Stable                    0.00  -6.42 <0.005     32.78
userReserveMode_USDC                   0.00  40.92 <0.005       inf

In [34]:
summary_df = model.summary
summary_df.head()

,coef,exp(coef),se(coef),coef lower 95%,coef upper 95%,exp(coef) lower 95%,exp(coef) upper 95%,cmp to,z,p,-log2(p)
covariate,,,,,,,,,,,
userActiveDaysWeekly,0.175140,1.191413,0.002160,0.170906,0.179374,1.186380,1.196468,0.0,81.081422,0.000000e+00,inf
marketLiquidationSumUSD,-0.022218,0.978027,0.002762,-0.027631,-0.016806,0.972747,0.983335,0.0,-8.045170,8.612584e-16,50.044403
marketLiquidationAvgAmountUSD,0.013923,1.014020,0.002371,0.009277,0.018569,1.009320,1.018743,0.0,5.873349,4.270789e-09,27.802850
userBorrowSum,-0.078968,0.924069,0.003110,-0.085064,-0.072873,0.918454,0.929719,0.0,-25.391962,3.093961e-142,470.084334
userDepositAvgAmountUSD,0.034029,1.034615,0.002282,0.029556,0.038502,1.029998,1.039253,0.0,14.911038,2.793753e-50,164.614200

In [ ]:
for index, row in summary_df.iterrows():
    if row['p'] >= 0.005:
        print(index)

marketWithdrawSumUSD
marketDepositCount
quarter
dayOfYear
cosDayOfWeek
priceInUSD
cosTimeOfDay
marketDepositSumUSD
marketDepositAvgAmount
isWeekend
userActiveDaysYearly
dayOfWeek

In [36]:
train_df.head()

,userActiveDaysWeekly,marketLiquidationSumUSD,marketLiquidationAvgAmountUSD,userBorrowSum,user,userDepositAvgAmountUSD,cosQuarter,userWithdrawAvgAmountUSD,userRepaySumUSD,userLiquidationAvgAmountUSD,...,amountUSD,userBorrowCount,cosDayOfQuarter,marketRepayCount,userBorrowSumUSD,userWithdrawSum,userDepositAvgAmount,userReserveMode,cosDayOfMonth,reserve
0,1.0,0.0,0.0,0.20000,0x4dee144e4d60ad8ae3e4b53e09669349dc0e23da,1.000000,6.123234e-17,0.0,0.0,0.0,...,0.199924,1,0.509933,0.0,0.199924,0.0,1.000000,DAI,-0.978148,other
1,1.0,0.0,0.0,0.79299,0x010afb8548a5d1a3a3d62f58ca0a5a1329974206,14.078625,6.123234e-17,0.0,0.0,0.0,...,0.793127,1,0.509933,0.0,0.793127,0.0,10.000000,DAI,-0.978148,other
2,1.0,0.0,0.0,1.00000,0x39d637737cc76c5849a52c7d3b872a1eb22aa71c,7.024463,6.123234e-17,0.0,0.0,0.0,...,0.999869,1,0.509933,0.0,0.999869,0.0,5.000000,USDC,-0.978148,USDC
3,1.0,0.0,0.0,15.00000,0x9f60699ce23f1ab86ec3e095b477ff79d4f409ad,27.100160,6.123234e-17,0.0,0.0,0.0,...,12.615414,3,0.509933,2.0,18.615467,0.0,26.500000,WPOL,-0.978148,WPOL
4,1.0,0.0,0.0,50.00000,0x005f16f017aa933bb41965b52848ceb8ee48b171,214.794320,6.123234e-17,0.0,0.0,0.0,...,55.015000,1,0.509933,2.0,55.015000,0.0,1.697614,jEUR,-0.978148,other

In [37]:
cols_list = ['marketWithdrawSumUSD', 'marketDepositCount', 'quarter', 'dayOfYear',
'cosDayOfWeek', 'priceInUSD', 'cosTimeOfDay', 'marketDepositSumUSD', 'marketDepositAvgAmount',
'isWeekend', 'userActiveDaysYearly', 'dayOfWeek']

In [38]:
new_train_df = train_df.drop(cols_list, axis=1)

In [ ]:
from utilities.preprocessing import preprocess
print("Preprocessing data...")
X_train, y_train, _ = preprocess(new_train_df)

Preprocessing data...
  - Dropping 3 zero-variance columns: ['userCoinTypeMode_Other', 'coinType_Other', 'reserve_Other']

In [40]:
from lifelines import CoxPHFitter

print("Training model on full training data...")
lifelines_train_df = pd.concat([X_train, y_train.reset_index(drop=True)], axis=1)
        
model = CoxPHFitter(penalizer=0.1)
model.fit(lifelines_train_df, duration_col='timeDiff', event_col='status')

Training model on full training data...

In [41]:
model.print_summary()

<lifelines.CoxPHFitter: fitted with 882736 total observations, 504835 right-censored observations>
             duration col = 'timeDiff'
                event col = 'status'
                penalizer = 0.1
                 l1 ratio = 0.0
      baseline estimation = breslow
   number of observations = 882736
number of events observed = 377901
   partial log-likelihood = -4935958.99
         time fit was run = 2025-09-17 19:17:29 UTC

---
                                     coef exp(coef)  se(coef)  coef lower 95%  coef upper 95% exp(coef) lower 95% exp(coef) upper 95%
covariate
userActiveDaysWeekly                 0.18      1.19      0.00            0.17            0.18                1.19                1.20
marketLiquidationSumUSD             -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
marketLiquidationAvgAmountUSD        0.01      1.01      0.00            0.01            0.02                1.01                1.02
userBorrowSum                       -0.08      0.92      0.00           -0.08           -0.07                0.92                0.93
userDepositAvgAmountUSD              0.03      1.03      0.00            0.03            0.04                1.03                1.04
cosQuarter                           0.01      1.01      0.00            0.00            0.01                1.00                1.01
userWithdrawAvgAmountUSD            -0.10      0.91      0.00           -0.10           -0.09                0.90                0.91
userRepaySumUSD                     -0.09      0.91      0.00           -0.10           -0.09                0.90                0.92
userLiquidationAvgAmountUSD          0.02      1.02      0.00            0.01            0.02                1.01                1.02
userRepayCount                      -0.17      0.84      0.00           -0.18           -0.16                0.84                0.85
cosDayOfYear                         0.05      1.05      0.00            0.04            0.05                1.04                1.05
userWithdrawAvgAmount               -0.05      0.95      0.00           -0.06           -0.05                0.94                0.95
marketRepayAvgAmount                -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
userBorrowAvgAmount                 -0.06      0.94      0.00           -0.06           -0.05                0.94                0.95
marketLiquidationCount               0.02      1.02      0.00            0.02            0.03                1.02                1.03
userSecondsSinceFirstTransaction     0.01      1.01      0.00            0.01            0.02                1.01                1.02
sinDayOfQuarter                     -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userDepositCount                     0.21      1.24      0.00            0.21            0.22                1.23                1.24
userRepayAvgAmount                   0.02      1.02      0.00            0.02            0.03                1.02                1.03
marketBorrowCount                    0.04      1.04      0.00            0.03            0.04                1.03                1.05
marketLiquidationAvgAmount           0.03      1.03      0.00            0.03            0.04                1.03                1.04
userWithdrawCount                    0.02      1.02      0.00            0.02            0.02                1.02                1.02
sinTimeOfDay                        -0.03      0.97      0.00           -0.03           -0.03                0.97                0.97
marketWithdrawCount                 -0.03      0.97      0.00           -0.04           -0.03                0.96                0.97
marketRepayAvgAmountUSD              0.03      1.03      0.00            0.03            0.04                1.03                1.04
amount                               0.01      1.01      0.00            0.01            0.02                1.01                1.02
userLiquidationAvgAmount             0.04      1.04      0.00            0.03            0.04                1.03                1.04
logAmount                            0.03      1.03      0.00            0.02            0.03                1.03                1.04
marketBorrowSum                      0.01      1.01      0.00            0.00            0.02                1.00                1.02
marketDepositAvgAmountUSD            0.02      1.02      0.00            0.02            0.03                1.02                1.03
marketRepaySum                       0.01      1.01      0.00            0.00            0.01                1.00                1.01
userDepositSumUSD                   -0.03      0.97      0.00           -0.03           -0.02                0.97                0.98
sinDayOfYear                         0.07      1.07      0.00            0.07            0.08                1.07                1.08
timeOfDay                            0.01      1.01      0.00            0.00            0.01                1.00                1.01
marketRepaySumUSD                    0.04      1.04      0.00            0.03            0.05                1.03                1.05
dayOfQuarter                         0.00      1.00      0.00            0.00            0.01                1.00                1.01
userSecondsSincePreviousTransaction -0.07      0.93      0.00           -0.07           -0.06                0.93                0.94
marketBorrowSumUSD                   0.04      1.04      0.00            0.04            0.05                1.04                1.05
userLiquidationSumUSD               -0.07      0.93      0.00           -0.07           -0.06                0.93                0.94
sinDayOfMonth                        0.01      1.01      0.00            0.01            0.02                1.01                1.02
userActiveDaysMonthly                0.16      1.17      0.00            0.16            0.16                1.17                1.18
sinDayOfWeek                        -0.00      1.00      0.00           -0.01            0.00                0.99                1.00
marketDepositSum                    -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
marketWithdrawSum                   -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketLiquidationSum                -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userRepayAvgAmountUSD               -0.03      0.97      0.00           -0.04           -0.02                0.96                0.98
dayOfMonth                          -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
marketWithdrawAvgAmountUSD           0.04      1.04      0.00            0.04            0.05                1.04                1.05
marketBorrowAvgAmountUSD             0.01      1.01      0.00            0.00            0.02                1.00                1.02
userDepositSum                      -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
userBorrowAvgAmountUSD              -0.11      0.90      0.00           -0.11           -0.10                0.89                0.90
marketBorrowAvgAmount               -0.02      0.98      0.00           -0.03           -0.02                0.97                0.98
userLiquidationCount                 0.07      1.07      0.00            0.06            0.07                1.06                1.07
userIsNew                           -0.98      0.37      0.03           -1.03           -0.93                0.36                0.39
sinQuarter                          -0.04      0.96      0.00           -0.04           -0.03                0.96                0.97
marketWithdrawAvgAmount              0.02      1.02      0.00            0.02            0.03                1.02                1.03
logAmountUSD                         0.14      1.15      0.00            0.14            0.15                1.15                1.16
userRepaySum                        -0.08      0.92      0.00           -0.08           -0.07                0.92                0.93
userLiquidationSum                   0.07      1.07      0.00            0.06            0.07                1.06                1.07
userWithdrawSumUSD                  -0.03      0.97      0.00           -0.04           -0.03                0.97                0.97
amountUSD                           -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
userBorrowCount                     -0.18      0.84      0.00           -0.19           -0.17                0.83                0.84
cosDayOfQuarter                     -0.02      0.99      0.00           -0.02           -0.01                0.98                0.99
marketRepayCount                    -0.01      0.99      0.00           -0.01           -0.00                0.99                1.00
userBorrowSumUSD                    -0.09      0.91      0.00           -0.10           -0.09                0.90                0.92
userWithdrawSum                     -0.02      0.98      0.00           -0.02           -0.01                0.98                0.99
userDepositAvgAmount                -0.01      0.99      0.00           -0.02           -0.01                0.98                0.99
cosDayOfMonth                        0.01      1.01      0.00            0.00            0.01                1.00                1.01
userCoinTypeMode_Stable              0.04      1.04      0.01            0.03            0.05                1.03                1.05
userCoinTypeMode_Non-Stable         -0.04      0.96      0.01           -0.05           -0.03                0.95                0.97
coinType_Stable                      0.04      1.04      0.01            0.03            0.05                1.03                1.05
coinType_Non-Stable                 -0.04      0.96      0.01           -0.05           -0.03                0.95                0.97
userReserveMode_USDC                 0.25      1.29      0.01            0.24            0.27                1.27                1.30
userReserveMode_DAI                 -0.16      0.85      0.01           -0.18           -0.15                0.84                0.86
userReserveMode_WPOL                -0.02      0.98      0.01           -0.04           -0.01                0.96                0.99
userReserveMode_WETH                 0.10      1.10      0.01            0.08            0.12                1.09                1.12
userReserveMode_USDT                -0.18      0.83      0.01           -0.20           -0.17                0.82                0.85
userReserveMode_WBTC                 0.24      1.28      0.01            0.22            0.27                1.25                1.31
userReserveMode_GHST                -0.76      0.47      0.01           -0.78           -0.74                0.46                0.48
userReserveMode_LINK                 0.21      1.24      0.01            0.19            0.24                1.21                1.27
userReserveMode_EURS                -0.22      0.80      0.02           -0.25           -0.18                0.78                0.83
userReserveMode_MaticX               0.35      1.42      0.02            0.32            0.38                1.37                1.47
userReserveMode_Other               -0.14      0.87      0.01           -0.16           -0.11                0.85                0.89
reserve_USDC                         0.25      1.29      0.01            0.24            0.27                1.27                1.30
reserve_other                       -0.27      0.76      0.01           -0.28           -0.26                0.75                0.77
reserve_WPOL                        -0.02      0.98      0.01           -0.04           -0.01                0.96                0.99
reserve_WETH                         0.10      1.10      0.01            0.08            0.12                1.09                1.12
reserve_USDT                        -0.18      0.83      0.01           -0.20           -0.17                0.82                0.85
reserve_WBTC                         0.24      1.28      0.01            0.22            0.27                1.25                1.31

                                     cmp to      z      p  -log2(p)
covariate
userActiveDaysWeekly                   0.00  81.66 <0.005       inf
marketLiquidationSumUSD                0.00  -8.06 <0.005     50.16
marketLiquidationAvgAmountUSD          0.00   6.06 <0.005     29.47
userBorrowSum                          0.00 -25.36 <0.005    468.94
userDepositAvgAmountUSD                0.00  14.81 <0.005    162.37
cosQuarter                             0.00   3.67 <0.005     12.02
userWithdrawAvgAmountUSD               0.00 -42.41 <0.005       inf
userRepaySumUSD                        0.00 -30.24 <0.005    664.83
userLiquidationAvgAmountUSD            0.00   8.69 <0.005     57.88
userRepayCount                         0.00 -55.71 <0.005       inf
cosDayOfYear                           0.00  20.36 <0.005    303.57
userWithdrawAvgAmount                  0.00 -18.94 <0.005    263.47
marketRepayAvgAmount                   0.00  -4.32 <0.005     15.97
userBorrowAvgAmount                    0.00 -20.02 <0.005    293.87
marketLiquidationCount                 0.00  10.27 <0.005     79.84
userSecondsSinceFirstTransaction       0.00   8.19 <0.005     51.82
sinDayOfQuarter                        0.00  -7.84 <0.005     47.63
userDepositCount                       0.00 101.38 <0.005       inf
userRepayAvgAmount                     0.00   8.69 <0.005     57.87
marketBorrowCount                      0.00  15.56 <0.005    178.83
marketLiquidationAvgAmount             0.00  12.62 <0.005    118.96
userWithdrawCount                      0.00  12.01 <0.005    107.89
sinTimeOfDay                           0.00 -16.26 <0.005    195.01
marketWithdrawCount                    0.00 -12.82 <0.005    122.53
marketRepayAvgAmountUSD                0.00  11.05 <0.005     91.81
amount                                 0.00   5.16 <0.005     21.96
userLiquidationAvgAmount               0.00  21.82 <0.005    348.37
logAmount                              0.00  11.78 <0.005    104.06
marketBorrowSum                        0.00   3.32 <0.005     10.14
marketDepositAvgAmountUSD              0.00   9.26 <0.005     65.46
marketRepaySum                         0.00   2.11   0.03      4.85
userDepositSumUSD                      0.00 -10.60 <0.005     84.84
sinDayOfYear                           0.00  29.27 <0.005    623.19
timeOfDay                              0.00   3.73 <0.005     12.34
marketRepaySumUSD                      0.00  13.16 <0.005    129.00
dayOfQuarter                           0.00   2.02   0.04      4.52
userSecondsSincePreviousTransaction    0.00 -32.23 <0.005    754.62
marketBorrowSumUSD                     0.00  14.07 <0.005    147.04
userLiquidationSumUSD                  0.00 -33.05 <0.005    793.52
sinDayOfMonth                          0.00   6.53 <0.005     33.82
userActiveDaysMonthly                  0.00  71.19 <0.005       inf
sinDayOfWeek                           0.00  -1.81   0.07      3.82
marketDepositSum                       0.00  -2.40   0.02      5.94
marketWithdrawSum                      0.00  -3.88 <0.005     13.21
marketLiquidationSum                   0.00  -7.01 <0.005     38.64
userRepayAvgAmountUSD                  0.00 -10.81 <0.005     88.05
dayOfMonth                             0.00  -6.49 <0.005     33.44
marketWithdrawAvgAmountUSD             0.00  16.80 <0.005    208.02
marketBorrowAvgAmountUSD               0.00   3.20 <0.005      9.50
userDepositSum                         0.00  -5.22 <0.005     22.43
userBorrowAvgAmountUSD                 0.00 -36.58 <0.005    970.52
marketBorrowAvgAmount                  0.00  -7.79 <0.005     47.12
userLiquidationCount                   0.00  47.29 <0.005       inf
userIsNew                              0.00 -36.41 <0.005    962.00
sinQuarter                             0.00 -17.91 <0.005    235.83
marketWithdrawAvgAmount                0.00   8.68 <0.005     57.77
logAmountUSD                           0.00  57.09 <0.005       inf
userRepaySum                           0.00 -25.33 <0.005    467.92
userLiquidationSum                     0.00  33.65 <0.005    822.42
userWithdrawSumUSD                     0.00 -13.06 <0.005    127.13
amountUSD                              0.00  -4.30 <0.005     15.87
userBorrowCount                        0.00 -59.04 <0.005       inf
cosDayOfQuarter                        0.00  -9.36 <0.005     66.81
marketRepayCount                       0.00  -3.59 <0.005     11.58
userBorrowSumUSD                       0.00 -30.26 <0.005    665.79
userWithdrawSum                        0.00  -8.11 <0.005     50.86
userDepositAvgAmount                   0.00  -6.56 <0.005     34.10
cosDayOfMonth                          0.00   3.64 <0.005     11.82
userCoinTypeMode_Stable                0.00   6.44 <0.005     32.98
userCoinTypeMode_Non-Stable            0.00  -6.44 <0.005     32.98
coinType_Stable                        0.00   6.44 <0.005     32.98
coinType_Non-Stable                    0.00  -6.44 <0.005     32.98
userReserveMode_USDC                   0.00  40.96 <0.005       inf
userReserveMode_DAI                    0.00 -23.29 <0.005    396.06
userReserveMode_WPOL                   0.00  -3.06 <0.005      8.84
userReserveMode_WETH                   0.00  11.74 <0.005    103.25
userReserveMode_USDT                   0.00 -22.02 <0.005    354.44
userReserveMode_WBTC                   0.00  19.88 <0.005    289.73
userReserveMode_GHST                   0.00 -62.76 <0.005       inf
userReserveMode_LINK                   0.00  15.01 <0.005    166.73
userReserveMode_EURS                   0.00 -12.14 <0.005    110.25
userReserveMode_MaticX                 0.00  20.72 <0.005    314.28
userReserveMode_Other                  0.00 -10.98 <0.005     90.70
reserve_USDC                           0.00  40.96 <0.005       inf
reserve_other                          0.00 -43.68 <0.005       inf
reserve_WPOL                           0.00  -3.06 <0.005      8.84
reserve_WETH                           0.00  11.74 <0.005    103.25
reserve_USDT                           0.00 -22.02 <0.005    354.44
reserve_WBTC                           0.00  19.88 <0.005    289.73
---
Concordance = 0.74
Partial AIC = 9872095.98
log-likelihood ratio test = 258198.53 on 89 df
-log2(p) of ll-ratio test = inf

In [42]:
# --- 4. Evaluate on Training Data ---
from utilities.cox_model import Model
from utilities.survival_metrics import get_concordance_index

print("Evaluating model on training data...")
wrapped_model_for_eval = Model(model)
train_preds = wrapped_model_for_eval.predict(X_train)
c_index_train = get_concordance_index(y_train, train_preds.values)
# training_scores[dataset_path] = c_index_train
print(f"  -> Training C-Index: {c_index_train:.4f}")

Evaluating model on training data...
  -> Training C-Index: 0.7407